 const deviceData = [
    {   id: 1,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:true,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 2,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },{   id: 3,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },{   id: 4,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },{   id: 5,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 6,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 7,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 8,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 9,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
    {   id: 10,
        deviceId: "546YTH73",
        deviceName: "Google Pixel 5",
        batteryLevel: "76%",
        isCharging:false,
        ipAddress: '168.223.112.42',
        macAddress: "Not Available",
        androidVersion:10,
        phoneNumber: 9058796195,
        carrier:"Glo",
        isConnected: true,
        isInternetReacheable:true,
        connectionType:"Cellular",
        location:"church str,Oworonshoki"
    },
]

export const mappedData = deviceData.map(item => ({
    id: item.id,
    deviceName:item.deviceName,
    deviceId:item.deviceId,
    batteryLevel:item.batteryLevel,
    isCharging:item.isCharging,
    ipAddress: item.ipAddress,
    macAddress:item.macAddress,
    androidVersion:item.androidVersion,
    phoneNumber: item.phoneNumber,
    carrier:item.carrier,
    isConnected:item.isConnected,
    connectionType:item.connectionType,
    isInternetReacheable:item.isInternetReacheable,
    location:item.location
}))

